### ISSUE TITLE
Improve performance of inserting/deleting units in the store

### ISSUE THREAD

**Issue by iafan** [evernote/pootle#145]
Currently each unit stores its position (index) in the .po file. Consider a .po file with 1000 units. If a new unit is added to the very top of the .po file, and then `update_stores` is run, the new unit will be created in the database, but in addition to that, 1000 units' position values will be updated (this is another 1000 DB updates). Inserting one unit into a large store can take several seconds. And this happens for each unit that is being inserted or deleted, which slows down the sync cycle.

There can be a number of optimization techniques for this. Here are a few:

1) wrap all unit-related changes into one transaction, which may speed things up and is good disregarding the current issue (this, though, requires moving to InnoDB engine).

2) don't store the position in each unit; instead, store a large blob in store, which lists an ordered list of unit ID's (e.g. comma-separated). This will mean that only one extra update will be needed per unit change, at the cost of some CPU work and extra processing logic.

3) Don't store the ordering at all, and read it by parsing .po (I guess .po files are parsed anyway before we try to update them). Cons: if the .po file is missing, we can't order the strings properly and will use some default sorting method. However, in our case the .po file will at some point get recreated with the correct unit ordering, anyway.

4) for units, store the link to next_unit as a DB field; when a unit is inserted or deleted, it will require only up to two additional DB updates for previous/next siblings. With this field, one can unwind an ordered chain of units.

**Comment by iafan** [comment]
@dwaynebailey, @ta2-1, @julen let's finally decide on our desired approach here, and we'll start implementing it.

**Comment by dwaynebailey** [comment]
So I've reread through this:

4) linked units - seemed viable but we're concerned about effort to maintain and use
5) index gaps - seems viable but requires periodic reindexing

For 4) I'd suggest we add two links, before and after.  I wonder if this model will be helpful going forward for continuous scroll editor?

Some other ideas:
6) Insert the block without indexes set and reindex apart from the insert of the units. I'm not sure how we determine the order post fact.
7) Normalize - would normalising the link between Store->Unit i.e Store->Link->Unit help at all? Or same problem with worse perf.

**Comment by ta2-1** [comment]
re 5): index should not be `integer`. It can be `float` or `string`. And then it seems the simplest solution. 

id | index | 4 after 1 | id | index | 5 after 4 | id | index | 6 after 4 | id | index 
--- | ----- | --------- | --- | ----- | --------- | --- | ----- | --------- | --- | ----- 
1 | 1 | | 1 | 1 | | 1 | 1 | | 1 | 1
2 | 2 | | 2 | 2 | | 2 | 2 | | 2 | 2
3 | 3 | | 3 | 3 | | 3 | 3 | | 3 | 3
 | | | 4 | 10 | | 4 | 10 | | 4 | 10
 | | | |  | | 5 | 11 | | 5 | 11
 | | | |  | | | | | 6 | 101

Reindexing also is supported.

re 4) how would we get default sorting order for unit selections?

**Comment by ta2-1** [comment]
We update store unit by unit. Note that after a changed unit is saved its index can be changed too but the rest of units in the store don't change their indexes. Because they should be changed during unit update itself.
8) If we insert new unit to place N we can run 
```sql
UPDATE index = index + 1 pootle_store_unit WHERE store_id = X AND index > N;
```
We get one extra query only. It makes sense it we insert one unit. But it wouldn't be very efficient in other cases.
I guess we should change the way how we apply changes from a file. Before performing any operation we are able to prepare a list of changes and then apply them using the most efficient algorithm in every case.

**Comment by iafan** [comment]
We just had a talk with @ta2-1, and this is the outcome:

Looks like the least risky variant for us at this point is:
1) to leave indices as integers (less DB migrations)
2) update the store update algorithm, so that when we're trying to insert N units after unit with index X, and the gap between X and next index Y is smaller than N, then run a query that shifts all indices starting with Y at once by the value of N-(Y-X) (which is cheap). Then do an insert.
3) Deleting a unit (or making it an obsolete one) shouldn't affect other units' indices. We just introduce a natural gap in numeration that can be reused later. Deleting units should be done before we insert new units, because the most common scenario is when the string is simply altered, which leads to deleting the old unit and creating the same unit at exactly the same index. In this case, no index shifting queries are necessary.

Thoughts?

**Comment by julen** [comment]
I'm fine with the approach provided we get unit tests with the change.

@dwaynebailey are we all on the same page? If so, let's re-create the issue at translate/pootle with the suggested way forward.

**Comment by dwaynebailey** [comment]
@julen also find with the approach, so please go ahead to port the issue to translate/pootle
